# Generated by Django 3.1.4 on 2021-01-07 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['start_at', 'end_at']},
        ),
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['banner', 'start_at']},
        ),
        migrations.AlterField(
            model_name='banner',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_banners', to='auth.user'),
        ),
    ]
