# Generated by Django 3.1.6 on 2021-03-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_auto_20210227_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='moderator',
        ),
        migrations.AddField(
            model_name='banner',
            name='moderator_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='banner',
            name='moderator_name',
            field=models.CharField(blank=True, max_length=127),
        ),
    ]
