# Generated by Django 3.1.6 on 2021-04-23 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0004_auto_20210306_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['start_at', 'end_at'], 'permissions': [('send_slot_reminders', 'Can initiate the pre-event reminder email to those who reserved slots')]},
        ),
    ]
