# Generated by Django 3.1.6 on 2021-04-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0005_auto_20210423_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
