version: '3.7'

services:
  web:
    build: .
    command: gunicorn prayerbanner.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/var/www/prayerbanner/staticfiles
    expose:
      - 8000
    env_file:
      - ./prayerbanner/.env
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/var/www/prayerbanner/staticfiles
    depends_on:
      - web

volumes:
  static_volume:
